# problem 2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

fib <- function(n) {
    x1 <- 0
    x2 <- 1
    for (i in 1:(n)) {
        xn <- x1 + x2
        x1 <- x2
        x2 <- xn 
    }
    return(x1)
}

y <- {}
x <- 1
while (fib(x) < 4000000) {
    if (length(y) == 0) {
        y <- fib(x) 
        x <- x + 1
    } else { 
        y <- c(y, fib(x)) 
        x <- x + 1
    }
}

sum(y[y %% 2 == 0])


def fib(n):
    x1 = 0
    x2 = 1
    for i in range(1,n+1):
            xn = x1 + x2
            x1 = x2
            x2 = xn
    return(xn)

